appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: gXglgwCVwTTd0wK4EpYDqHaJh6tUTid9XOCL7OdmT9qwLXQI0knpTki1sEKhd3lkRSNFFuSC3TwpBqXXAPGUEZrUV/OdvlGRJlH8mgLEA0BkUP5SCtKgH3AF03hwMNctK8i6mxihghQENjbGvZEQCxjhWpKhHUV9Nn1uUTu5O/9LFSSxPqGAKTRtVyEvPuhT1PIL03q+xctoSfPoJdLG3LCmZRkB267rKQLkS4tsmcVl76fjQmfVSVr5N37GsXg5mPDG1+4P8Jq7VrXrW3rmwv7QpqObhlYZKPGUpt59LjVIygc96OmsJkTl6GRMwtyQB9sDIHmvwXRsxUlplQUSC1FylD4KbtmurPAu5oeZvfH16MNRGfCe20C5NUJLX5JQQYzH14Mol7DHy6M6jcEXk1RnyW1zgzhfCvw3OYZZiTzHAC1UiI3q93YuWHHYcVa3UxqS61uNMv1cDe+f/76VP8Wrk0uggPvwxKwEd5WfHgYG78Vk8x+M4Ekgw3TNxSZujevikYaFWwYzzCfrNu1kGb6fiSyhJH7wI9hOWV2um7dW5zKK2ce2BB6Dba3JLN8o7HxUrk7bIE17YFqBY6QqUognIkwhwD1WLaDzbus9/zkPlA8tvOL3burRsSoyaRWpwRiXIJ01f1WSHaDWyKTkq6m7tMANNZt5VTHrFM8uML0=
conda_forge_output_validation: false
